//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUII.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Departman Id zorunludur")]
        public int DepartmanId { get; set; }
        [Required(ErrorMessage = "Ad zorunludur")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyad zorunludur")]
        public string Soyad { get; set; }
        [Required(ErrorMessage = "Maaþ zorunludur")]
        public Nullable<short> Maas { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
